apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deploy
  labels:
    app: vprofile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: demo
  template:
    metadata:
    name: vprofile-pod
    labels:
      app: vprofile-app
      tier: demo
    spec:
      containers:
      - name: vprofile-contianer
        image: oludevops/vprofile




