apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deploy
  labels:
    app: vprofile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: demo
  template:
    metadata:
      name: vprofile-pod
      labels:
        app: vprofile-app
        tier: demo
    spec:
      containers:
      - name: vprofile-contianer
        image: oludocker/vprofile
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-app
spec:
  selector:
    app: vprofile-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort


